apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: analytics-service
  namespace: default
spec:
  owner:
    projectName: url-shortener
  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 7544
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    readinessProbe:
      httpGet:
        path: /health
        port: 7544
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /health
        port: 7544
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: analytics-service
  namespace: default
spec:
  owner:
    componentName: analytics-service
    projectName: url-shortener
  containers:
    main:
      image: rashadxyz/url-shortener-analytics:v1
      env:
        - key: PORT
          value: "7544"
        - key: DATABASE_URL
          value: "postgresql://urlshortener:password123@postgres:80/urlshortener"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.openchoreo-observability-plane.svc.cluster.local:4318"
