apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: api-service
  namespace: default
spec:
  owner:
    projectName: url-shortener
  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 7543
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    readinessProbe:
      httpGet:
        path: /health
        port: 7543
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /health
        port: 7543
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: api-service
  namespace: default
spec:
  owner:
    componentName: api-service
    projectName: url-shortener
  containers:
    main:
      image: rashadxyz/url-shortener-api:v1
      env:
        - key: PORT
          value: "7543"
        - key: DATABASE_URL
          value: "postgres://urlshortener:password123@postgres:80/urlshortener?sslmode=disable"
        - key: REDIS_URL
          value: "redis:80"
        - key: CACHE_TTL
          value: "120"
        - key: RATE_LIMIT_REQUESTS
          value: "100"
        - key: RATE_LIMIT_WINDOW
          value: "60"
        - key: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector.openchoreo-observability-plane.svc.cluster.local:4318"
