apiVersion: openchoreo.dev/v1alpha1
kind: Project
metadata:
  annotations:
    openchoreo.dev/description: URL shortener demo
    openchoreo.dev/display-name: URL Shortener Demo
  labels:
    openchoreo.dev/name: url-shortener
    openchoreo.dev/organization: default
  name: url-shortener
  namespace: default
spec:
  deploymentPipelineRef: default
